library(shiny)

shinyUI(fluidPage(
  title = "BTACT Factor Score and Norms Calculator",
  fluidRow(
    column(8,
           h2("BTACT Factor Score and Norms Calculator")),
    column(4,
           img(src = "http://www.uccs.edu/Images/brand/uccs-logo.png", width=400, height=58))),
  fluidRow(HTML("Based on Gavett, B. E., Crane, P. K., & Dams-O'Connor, K. (2013). Bi-factor analyses of the Brief Test of Adult Cognition by Telephone. <i>NeuroRehabilitation</i>, <i>32</i>, 253-365. <a href = 'http://www.uccs.edu/Documents/bgavett/BTACT_2013.pdf'><img src = 'http://www.adobe.com/images/pdficon_small.png'></a>")),
  tags$hr(),
  fluidRow(
    column(3,
           numericInput("b_digit", "Backward Digit Span (0-7):",0,min=0,max=7),
           numericInput("ns_1", "Number Series Trial 1 (0-1):",0,min=0,max=1),
           numericInput("ns_2", "Number Series Trial 2 (0-1):",0,min=0,max=1),
           numericInput("ns_3", "Number Series Trial 3 (0-1):",0,min=0,max=1),
           numericInput("ns_4", "Number Series Trial 4 (0-1):",0,min=0,max=1),
           numericInput("ns_5", "Number Series Trial 5 (0-1):",0,min=0,max=1),
           numericInput("wli_early", "Immediate Word List Trials 1-5 (0-5):",0,min=0,max=5),
           numericInput("wli_mid", "Immediate Word List Trials 6-10 (0-5):",0,min=0,max=5),
           numericInput("wli_late", "Immediate Word List Trials 11-15 (0-5):",0,min=0,max=5),
           numericInput("wld_early", "Delayed Word List Trials 1-5 (0-5):",0,min=0,max=5),
           numericInput("wld_mid", "Delayed Word List Trials 6-10 (0-5):",0,min=0,max=5),
           numericInput("wld_late", "Delayed Word List Trials 11-15 (0-5):",0,min=0,max=5),
           numericInput("rg_norm_switch", "Red-Green Test Normal Switching Condition (0-3):",0,min=0,max=3),
           numericInput("rg_rev_switch", "Red-Green Test Reverse Switching Condition (0-3):",0,min=0,max=3),
           numericInput("prg_rev_other", "Red-Green Test Reverse Other Condition (0-11):",0,min=0,max=11),
           numericInput("prg_norm_other", "Red-Green Test Normal Other Condition (0-15):",0,min=0,max=15),
           numericInput("pcat", "Category Fluency (0-100):",0,min=0,max=100),
           numericInput("pbc_score", "Backwards Counting (0-100):",0,min=0,max=100)),
    column(3,
           numericInput("age", "Age (28-84):",28,min=28,max=84),
           radioButtons("edu", "Education:",
                        c("0-6 Years" = "Grade",
                          "7-8 Years" = "Junior",
                          "9-12 Years" = "SomeHigh",
                          "GED" = "GED",
                          "High School Graduate" = "High",
                          "1-2 Years of College, no Degreee" = "SomeCol1-2",
                          "3+ Years of College, no Degree" = "SomeCol3+",
                          "Graduated from 2 Year College, Vocational School, or Associate's Degree" = "Assoc",
                          "Graduated from 4 or 5 Year College, or Bachelor's Degree" = "BA",
                          "Some Graduate School" = "SomeGrad",
                          "Master's Degree" = "MA",
                          "Ph.D., Ed.D, MD, DDS, LLB, LLD, JD, or other Professional Degree" = "PhD")),
           radioButtons("gender", "Gender:",
                        c("Female" = "Female",
                          "Male" = "Male")),
           radioButtons("occ", "Occupation:",
                        c("Operator, Laborer, and Military" = "Labor",
                          "Executive, Administrative, and Managerial" = "Exec",
                          "Professional Specialty" = "Prof",
                          "Technician and Related Support" = "Tech",
                          "Sales Occupation" = "Sales",
                          "Administrative Support, Including Clerical" = "Admin",
                          "Service Occupation" = "Service",
                          "Farming, Forestry, and Fishing" = "FFF",
                          "Precision Production, Crafts, and Repair" = "Repair"
                        ))
    ),
    column(1,
           submitButton("Calculate")),
    column(5,
           tabsetPanel(
             tabPanel("Unadjusted",
                      h4("BTACT Factor z-scores (M = 0, SD = 1)"),
                      tableOutput("FScoresN")),
             tabPanel("Age",
                      h4("BTACT Factor z-scores (M = 0, SD = 1)"),
                      tableOutput("FScoresA")),
             tabPanel("A + Edu",
                      h4("BTACT Factor z-scores (M = 0, SD = 1)"),
                      tableOutput("FScoresAE")),
             tabPanel("A + Gen",
                      h4("BTACT Factor z-scores (M = 0, SD = 1)"),
                      tableOutput("FScoresAG")),
             tabPanel("A + Occu",
                      h4("BTACT Factor z-scores (M = 0, SD = 1)"),
                      tableOutput("FScoresAO")),
             tabPanel("A + E + G",
                      h4("BTACT Factor z-scores (M = 0, SD = 1)"),
                      tableOutput("FScoresAEG")),
             tabPanel("A + E + O",
                      h4("BTACT Factor z-scores (M = 0, SD = 1)"),
                      tableOutput("FScoresAEO")),
             tabPanel("A + G + O",
                      h4("BTACT Factor z-scores (M = 0, SD = 1)"),
                      tableOutput("FScoresAGO")),
             tabPanel("A + E + G + O",
                      h4("BTACT Factor z-scores (M = 0, SD = 1)"),
                      tableOutput("FScoresAEGO"))
           )
    )
  )))